# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetStockPirce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetStockPirce
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod "SwiftSpinner"
  pod "PromiseKit", "~> 6.8"
  pod 'KeychainSwift', '~> 20.0'

end
